import streamlit as st
import pandas as pd
import sys
import os

# This ensures Streamlit can find our backend folder
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
from backend.agent.graph import app as finops_workflow

# Set up the page layout
st.set_page_config(page_title="FinOps Agent", layout="wide")

st.title("🤖 Enterprise Autonomous FinOps Agent")
st.markdown("Upload your AWS Cost & Usage Report. Our multi-agent AI will analyze anomalies and generate remediation scripts.")

# 1. File Upload UI
uploaded_file = st.file_uploader("Upload Mock Billing CSV", type=["csv"])

if uploaded_file is not None:
    # Save the file temporarily so Pandas can read it
    temp_path = "data/temp_uploaded_billing.csv"
    with open(temp_path, "wb") as f:
        f.write(uploaded_file.getbuffer())
        
    st.success("File uploaded successfully!")
    
    # Let the user preview the data they uploaded
    with st.expander("Preview Uploaded Data"):
        df = pd.read_csv(temp_path)
        st.dataframe(df.head(10))
        
    # 2. Trigger the AI Workflow
    if st.button("Run FinOps Audit", type="primary"):
        with st.spinner("AI Agents are analyzing your infrastructure... (This takes 10-20 seconds)"):
            
            # We trigger the exact same LangGraph we ran in the terminal!
            initial_state = {"raw_csv_path": temp_path}
            final_state = finops_workflow.invoke(initial_state)
            
            # Save the results in Streamlit's memory so they don't disappear when the page reloads
            st.session_state['workflow_results'] = final_state

# 3. Display the Results & Human-In-The-Loop (HITL)
if 'workflow_results' in st.session_state:
    st.divider()
    results = st.session_state['workflow_results']
    
    # Create two columns for a nice dashboard layout
    col1, col2 = st.columns([1, 1])
    
    with col1:
        st.header("👔 Executive Report")
        st.info("Generated by the Synthesis Agent")
        st.markdown(results['executive_report'])
        
    with col2:
        st.header("⚙️ Remediation Code")
        st.warning("Generated by the DevOps Agent. Awaiting Approval.")
        st.code(results['remediation_code'], language='python')
        
    # 4. The HITL Gateway (Approval Buttons)
    st.divider()
    st.header("🛑 Human-In-The-Loop Approval")
    
    approve_col, reject_col = st.columns(2)
    with approve_col:
        if st.button("✅ Approve & Execute Changes"):
            st.success("Changes Approved! (In a real production environment, this would execute the Boto3 script).")
    with reject_col:
        if st.button("❌ Reject"):
            st.error("Execution halted.")
