# Use the official AWS Lambda Python base image
FROM public.ecr.aws/lambda/python:3.9

# Copy requirements file
COPY requirements-lambda.txt ${LAMBDA_TASK_ROOT}

# Upgrade pip to prevent pyarrow from building from source
RUN pip install --upgrade pip

# Install dependencies
RUN pip install --no-cache-dir -r requirements-lambda.txt

# Copy all application code into the Lambda task root
COPY backend/ ${LAMBDA_TASK_ROOT}/backend/
COPY data/ ${LAMBDA_TASK_ROOT}/data/

# Set the CMD to your Lambda handler
CMD [ "backend.lambda_function.lambda_handler" ]
